INCLUDES+=-Iinclude -DPLIST_NO_XML

SRCS=src/Array.cpp src/Boolean.cpp src/bplist.c src/Data.cpp src/Date.cpp src/Dictionary.cpp src/Integer.cpp src/Node.cpp src/plist.c src/Real.cpp src/String.cpp src/Structure.cpp

LIB= libplist.a

include ../../../Makefile.include

