#!/bin/sh

# Script name can be the called name, or something more meaningful.
SCRIPTNAME=$0

. /etc/init.d/init_utilities

start_function() {
    mkdir -p /opt/local/var/run/avahi-daemon
    LD_LIBRARY_PATH=/opt/local/lib /opt/local/sbin/avahi-daemon -D
}

stop_function() {
    # Terminate daemons, remove modules, remove device nodes here
    PID=`ps -ef | grep -v grep | grep "/opt/local/bin/avahi-daemon" | awk '{print $2}'`
    if [[ "x$PID" == "x" ]]; then 
        echo "avahi not running; cannot kill"
    else
        kill $PID
    fi
}

case $1 in
    "start")
    start_function
    ;;
    "stop")
    stop_function
    ;;
    "restart")
    stop_function
    start_function
    ;;
    *)
    echo "Usage: $0 {start|stop|restart}"
esac
