#!/bin/sh

# Script name can be the called name, or something more meaningful.
SCRIPTNAME=$0

. /etc/init.d/init_utilities

start_function() {
    # Start Boxee if so equipped
    debug_print "Trying to start Boxee Launcher"
    while [ ! -z `pidof "cl_app"`  ]; do
    	sleep 1;
    done
    try_command /opt/boxee/BoxeeLauncher &
}

stop_function() {
    # Terminate daemons, remove modules, remove device nodes here
    BH_PID=`ps -ef | grep -v grep | grep "/opt/boxee/BoxeeLauncher" | awk '{print $2}'`
    if [[ "x$BH_PID" == "x" ]]; then 
        echo "Boxee Launcher not running; cannot kill"
    else
        kill $BH_PID
    fi
}

case $1 in
    "start")
    start_function
    ;;
    "stop")
    stop_function
    ;;
    "restart")
    stop_function
    start_function
    ;;
    *)
    echo "Usage: $0 {start|stop|restart}"
esac
