#!/bin/sh

#  This file is provided under a dual BSD/GPLv2 license.  When using or 
#  redistributing this file, you may do so under either license.
#
#  GPL LICENSE SUMMARY
#
#  Copyright(c) 2007-2009 Intel Corporation. All rights reserved.
#
#  This program is free software; you can redistribute it and/or modify 
#  it under the terms of version 2 of the GNU General Public License as
#  published by the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful, but 
#  WITHOUT ANY WARRANTY; without even the implied warranty of 
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License 
#  along with this program; if not, write to the Free Software 
#  Foundation, Inc., 51 Franklin St - Fifth Floor, Boston, MA 02110-1301 USA.
#  The full GNU General Public License is included in this distribution 
#  in the file called LICENSE.GPL.
#
#  Contact Information:
#  intel.com
#  Intel Corporation
#  2200 Mission College Blvd.
#  Santa Clara, CA  95052
#  USA
#  (408) 765-8080
#
# =========================================================================

# Script name can be the called name, or something more meaningful.
SCRIPTNAME=$0
PATH=/usr/local/bin:/usr/bin:/bin:/sbin

. /etc/init.d/init_utilities

start_function() {
    # Install modules, make device nodes, start daemons here
    mkdir -p /var/lib/dhcpv6
    mkdir -p /var/run/dhcpv6
    # create supporting dirs
    TMPDIRS=".adobe .macromedia .qws .smb mnt media nand smblock"
    for t in $TMPDIRS
    do
        debug_print "Creating /tmp/$t"
        mkdir /tmp/$t > /dev/null 2>&1
    done
    chmod 0755 /tmp/smblock
    # start udev
    try_command udevd -d
    try_command udevadm trigger
}

stop_function() {
    # Terminate daemons, remove modules, remove device nodes here
    rm -rf /var/lib/dhcpv6
    rm -rf /var/run/dhcpv6
    # kill udev
    killall udevd
}

case $1 in
    "start")
        start_function
        ;;
    "stop")
        stop_function
        ;;
    "restart")
        stop_function
        start_function
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
esac
