#!/bin/sh

# Script name can be the called name, or something more meaningful.
SCRIPTNAME=network
PATH=/usr/local/bin:/usr/bin:/bin:/sbin

. /etc/init.d/init_utilities

start_function() {
    ifconfig eth0 up

    # Add an entry to the routing table
    route add -net 224.0.0.0 netmask 240.0.0.0 eth0

    # Set up the local loopback device
    ifconfig lo 127.0.0.1
}

stop_function() {
    # Remove our entry from the routing table
    route del -net 224.0.0.0 netmask 240.0.0.0 eth0
}

case $1 in
    "start")
        start_function
        ;;
    "stop")
        stop_function
        ;;
    "restart")
        stop_function
        start_function
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
esac
