#!/bin/sh

# Script name can be the called name, or something more meaningful.
SCRIPTNAME=$0

. /etc/init.d/init_utilities

start_function() {
    # Start smbd if so equipped
    if [ ! -f /data/etc/smb.disabled ]; then
        debug_print "Trying to start smbd"
        try_command /opt/local/sbin/smbd -s /data/etc/smb.conf
    else
        debug_print "Samba is disabled."
    fi
}

stop_function() {
    # Terminate daemons, remove modules, remove device nodes here
    SMBD_PID=`ps -ef | grep -v grep | grep "/opt/local/sbin/smbd" | awk '{print $2}'`
    if [[ "x$SMBD_PID" == "x" ]]; then
        echo "smbd not running; cannot kill"
    else
        kill $SMBD_PID
    fi
}

case $1 in
    "start")
    start_function
    ;;
    "stop")
    stop_function
    ;;
    "restart")
    stop_function
    start_function
    ;;
    *)
    echo "Usage: $0 {start|stop|restart}"
esac
