#pragma once
/*
 *      Copyright (C) 2005-2010 Team XBMC
 *      http://www.xbmc.org
 *
 *  This Program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2, or (at your option)
 *  any later version.
 *
 *  This Program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with XBMC; see the file COPYING.  If not, write to
 *  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 *  http://www.gnu.org/copyleft/gpl.html
 *
 */

namespace JSONRPC
{
  const char* const JSON_SERVICE_DESCRIPTION = 
"  {"
"    \"id\": \"http://www.boxee.tv/jsonrpc.jsd\","
"    \"version\": 1,"
"    \"description\": \"JSON RPC API of BOXEE (somewhat compatible with XBMC)\","
""
"    \"JSONRPC.Introspect\": {"
"        \"type\": \"method\","
"        \"description\": \"Enumerates all actions and descriptions\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": ["
"            { \"name\": \"getdescriptions\", \"type\": \"boolean\", \"default\": true }"
""
""
""
""
""
"        ],"
"        \"returns\": \"object\""
"    },"
"    \"JSONRPC.Version\": {"
"        \"type\": \"method\","
"        \"description\": \"Retrieve the jsonrpc protocol version\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"JSONRPC.Permission\": {"
"        \"type\": \"method\","
"        \"description\": \"Retrieve the clients permissions\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": {"
"            \"type\": \"object\","
"            \"properties\": {"
"                \"ReadData\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
"                \"ControlPlayback\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
"                \"ControlNotify\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
"                \"ControlPower\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
"                \"Logging\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
"                \"ScanLibrary\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
"                \"GUI\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" }"
"            }"
"        }"
"    },"
"    \"JSONRPC.Ping\": {"
"        \"type\": \"method\","
"        \"description\": \"Ping responder\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"JSONRPC.GetNotificationFlags\": {"
"        \"type\": \"method\","
"        \"description\": \"Get notification flags\","
"        \"transport\": \"Announcing\","
"        \"permission\": \"ReadData\","
"        \"params\": [],"
"        \"returns\": {"
"            \"id\": \"Notification.Flags\","
"            \"type\": \"object\","
"            \"properties\": {"
"                \"Playback\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
"                \"GUI\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
"                \"System\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
"                \"Library\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
"                \"Other\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" }"
"            }"
"        }"
"    },"
"    \"JSONRPC.SetNotificationFlags\": {"
"        \"type\": \"method\","
"        \"description\": \"Change the notification flags\","
"        \"transport\": \"Announcing\","
"        \"permission\": \"ControlNotify\","
"        \"params\": ["
"            { \"name\": \"Playback\", \"type\": \"boolean\", \"default\": false },"
"            { \"name\": \"GUI\", \"type\": \"boolean\", \"default\": false },"
"            { \"name\": \"System\", \"type\": \"boolean\", \"default\": false },"
"            { \"name\": \"Library\", \"type\": \"boolean\", \"default\": false },"
"            { \"name\": \"Other\", \"type\": \"boolean\", \"default\": false }"
"        ],"
"        \"returns\": { \"$ref\": \"Notification.Flags\" }"
"    },"
"    \"JSONRPC.Notify\": {"
"        \"type\": \"method\","
"        \"description\": \"Notify other connected clients\","
"        \"transport\": \"Response\","
"        \"permission\": \"ReadData\","
"        \"params\": ["
"            { \"name\": \"sender\", \"type\": \"string\", \"required\": true },"
"            { \"name\": \"message\", \"type\": \"string\", \"required\": true },"
"            { \"name\": \"data\", \"type\": \"any\", \"default\": null }"
"        ],"
"        \"returns\": \"any\""
"    },"
"    \"Player.GetActivePlayers\": {"
"        \"type\": \"method\","
"        \"description\": \"Returns all active players\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": {"
"            \"type\": \"object\","
"            \"properties\": {"
"                \"video\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
"                \"audio\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
"                \"picture\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" }"
""
"              , \"browser\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" }"
""
"            }"
"        }"
"    },"
"    \"AudioPlayer.State\": {"
"        \"type\": \"method\","
"        \"description\": \"Returns playback state of the audio player (if it is active)\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": {"
"            \"id\": \"Player.State.Extended\","
"            \"type\": \"object\","
"            \"properties\": {"
"                \"playing\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
"                \"paused\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
""
"                \"stream\": { \"type\": \"string\", \"required\": false, \"description\": \"\" },"
"                \"label\": { \"type\": \"string\", \"required\": false, \"description\": \"\" },"
"                \"seekable\": { \"type\": \"boolean\", \"required\": false, \"description\": \"\" },"
"                \"can-play-next\": { \"type\": \"boolean\", \"required\": false, \"description\": \"\" },"
"                \"can-play-prev\": { \"type\": \"boolean\", \"required\": false, \"description\": \"\" }"
""
""
""
"            }"
"        }"
"    },"
"    \"AudioPlayer.PlayPause\": {"
"        \"type\": \"method\","
"        \"description\": \"Pauses or unpause playback and returns the new state\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": {"
"            \"id\": \"Player.State\","
"            \"type\": \"object\","
"            \"properties\": {"
"                \"playing\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
"                \"paused\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" }"
"            }"
"        }"
"    },"
"    \"AudioPlayer.Stop\": {"
"        \"type\": \"method\","
"        \"description\": \"Stops playback\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"AudioPlayer.SkipPrevious\": {"
"        \"type\": \"method\","
"        \"description\": \"Skips to previous item on the playlist\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"AudioPlayer.SkipNext\": {"
"        \"type\": \"method\","
"        \"description\": \"Skips to next item on the playlist\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"AudioPlayer.BigSkipBackward\": {"
"        \"type\": \"method\","
"        \"description\": \"\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"AudioPlayer.BigSkipForward\": {"
"        \"type\": \"method\","
"        \"description\": \"\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"AudioPlayer.SmallSkipBackward\": {"
"        \"type\": \"method\","
"        \"description\": \"\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"AudioPlayer.SmallSkipForward\": {"
"        \"type\": \"method\","
"        \"description\": \"\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"AudioPlayer.GetTime\": {"
"        \"type\": \"method\","
"        \"description\": \"Retrieves the current and total time of the currently playing file\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": {"
"            \"id\": \"Player.TimeValues\","
"            \"type\": \"object\","
"            \"properties\": {"
"                \"time\": { \"type\": \"object\", \"id\": \"Global.Time\", \"required\": true, \"description\": \"\","
"                    \"properties\": {"
"                        \"hours\": { \"type\": \"integer\", \"required\": true, \"minimum\": 0, \"maximum\": 23 },"
"                        \"minutes\": { \"type\": \"integer\", \"required\": true, \"minimum\": 0, \"maximum\": 59 },"
"                        \"seconds\": { \"type\": \"integer\", \"required\": true, \"minimum\": 0, \"maximum\": 59 },"
"                        \"milliseconds\": { \"type\": \"integer\", \"required\": true, \"minimum\": 0, \"maximum\": 999 }"
"                    }"
"                },"
"                \"total\": { \"$ref\": \"Global.Time\", \"required\": true, \"description\": \"\" },"
"                \"playing\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
"                \"paused\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" }"
"            }"
"        }"
"    },"
"    \"AudioPlayer.GetPercentage\": {"
"        \"type\": \"method\","
"        \"description\": \"Retrieve current playback progress in percentage\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"number\""
"    },"
"    \"AudioPlayer.SeekTime\": {"
"        \"type\": \"method\","
"        \"description\": \"Seek to a specific time\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": ["
"            { \"name\": \"value\", \"id\": \"Player.SeekTime\", \"type\": \"integer\", \"required\": true, \"minimum\": 0, \"description\": \"Time to seek to in seconds\" }"
"        ],"
"        \"returns\": \"string\""
"    },"
"    \"AudioPlayer.SeekPercentage\": {"
"        \"type\": \"method\","
"        \"description\": \"Seek to a specific percentage\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": ["
"            { \"name\": \"value\", \"id\": \"Player.SeekPercentage\", \"type\": \"number\", \"required\": true, \"minimum\": 0.0, \"maximum\": 100.0, \"description\": \"Percentage value to seek to\" }"
"        ],"
"        \"returns\": \"string\""
"    },"
"    \"VideoPlayer.State\": {"
"        \"type\": \"method\","
"        \"description\": \"Returns playback state of the video player (if it is active)\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": { \"$ref\": \"Player.State.Extended\" }"
"    },"
"    \"VideoPlayer.PlayPause\": {"
"        \"type\": \"method\","
"        \"description\": \"Pauses or unpause playback and returns the new state\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": { \"$ref\": \"Player.State\" }"
"    },"
"    \"VideoPlayer.Stop\": {"
"        \"type\": \"method\","
"        \"description\": \"Stops playback\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"VideoPlayer.SkipPrevious\": {"
"        \"type\": \"method\","
"        \"description\": \"Skips to previous item on the playlist\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"VideoPlayer.SkipNext\": {"
"        \"type\": \"method\","
"        \"description\": \"Skips to next item on the playlist\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"VideoPlayer.BigSkipBackward\": {"
"        \"type\": \"method\","
"        \"description\": \"\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"VideoPlayer.BigSkipForward\": {"
"        \"type\": \"method\","
"        \"description\": \"\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"VideoPlayer.SmallSkipBackward\": {"
"        \"type\": \"method\","
"        \"description\": \"\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"VideoPlayer.SmallSkipForward\": {"
"        \"type\": \"method\","
"        \"description\": \"\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"VideoPlayer.GetTime\": {"
"        \"type\": \"method\","
"        \"description\": \"Retrieves the current and total time of the currently playing file\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": { \"$ref\": \"Player.TimeValues\" }"
"    },"
"    \"VideoPlayer.GetPercentage\": {"
"        \"type\": \"method\","
"        \"description\": \"Retrieve current playback progress in percentage\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"number\""
"    },"
"    \"VideoPlayer.SeekTime\": {"
"        \"type\": \"method\","
"        \"description\": \"Seek to a specific time\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": ["
"            { \"name\": \"value\", \"$ref\": \"Player.SeekTime\", \"required\": true }"
"        ],"
"        \"returns\": \"string\""
"    },"
"    \"VideoPlayer.SeekPercentage\": {"
"        \"type\": \"method\","
"        \"description\": \"Seek to a specific percentage\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": ["
"            { \"name\": \"value\", \"$ref\": \"Player.SeekPercentage\", \"required\": true }"
"        ],"
"        \"returns\": \"string\""
"    },"
"    \"PicturePlayer.PlayPause\": {"
"        \"type\": \"method\","
"        \"description\": \"Pauses or unpause slideshow\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"PicturePlayer.Stop\": {"
"        \"type\": \"method\","
"        \"description\": \"Stops slideshow\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"PicturePlayer.SkipPrevious\": {"
"        \"type\": \"method\","
"        \"description\": \"Skips to previous picture in the slideshow\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"PicturePlayer.SkipNext\": {"
"        \"type\": \"method\","
"        \"description\": \"Skips to next picture in the slideshow\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"PicturePlayer.MoveLeft\": {"
"        \"type\": \"method\","
"        \"description\": \"If picture is zoomed move viewport left otherwise skip previous\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"PicturePlayer.MoveRight\": {"
"        \"type\": \"method\","
"        \"description\": \"If picture is zoomed move viewport right otherwise skip next\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"PicturePlayer.MoveDown\": {"
"        \"type\": \"method\","
"        \"description\": \"If picture is zoomed move viewport down\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"PicturePlayer.MoveUp\": {"
"        \"type\": \"method\","
"        \"description\": \"If picture is zoomed move viewport up\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"PicturePlayer.ZoomOut\": {"
"        \"type\": \"method\","
"        \"description\": \"Zoom out once\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"PicturePlayer.ZoomIn\": {"
"        \"type\": \"method\","
"        \"description\": \"Zoom in once\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"PicturePlayer.Zoom\": {"
"        \"type\": \"method\","
"        \"description\": \"Zooms current picture\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": ["
"            { \"name\": \"value\", \"type\": \"integer\", \"required\": true, \"minimum\": 1, \"maximum\": 10, \"description\": \"Zoom level\" }"
"        ],"
"        \"returns\": \"string\""
"    },"
"    \"PicturePlayer.Rotate\": {"
"        \"type\": \"method\","
"        \"description\": \"Rotates current picture\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"Files.GetSources\": {"
"        \"type\": \"method\","
"        \"description\": \"Get the sources of the media windows\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": ["
"            { \"name\": \"media\", \"id\": \"Files.Media\", \"type\": \"string\", \"required\": true, \"enum\": [ \"video\", \"music\", \"pictures\", \"files\""
"               ] },"
"            { \"name\": \"limits\", \"id\": \"List.Limits\", \"type\": \"object\", \"required\": false,"
"                \"properties\": {"
"                    \"start\": { \"type\": \"integer\", \"minimum\": 0, \"default\": 0 },"
"                    \"end\": { \"type\": \"integer\", \"minimum\": 0, \"default\": -1 }"
"                }"
"            }"
"        ],"
"        \"returns\": {"
"            \"type\": \"object\","
"            \"properties\": {"
"                \"limits\": { \"type\": \"object\", \"id\": \"List.LimitsReturned\", \"required\": true,"
"                    \"properties\": {"
"                        \"start\": { \"type\": \"integer\", \"minimum\": 0, \"required\": true },"
"                        \"end\": { \"type\": \"integer\", \"minimum\": 0, \"required\": true },"
"                        \"total\": { \"type\": \"integer\", \"minimum\": 0, \"required\": true }"
"                    }"
"                },"
"                \"shares\": { \"type\": \"array\", \"id\": \"Files.Items\","
"                    \"items\": {"
"                        \"type\": \"object\","
"                        \"properties\": {"
"                            \"file\": { \"type\": \"string\", \"required\": true },"
"                            \"label\": { \"type\": \"string\", \"required\": true }"
"                        }"
"                    }"
"                }"
"            }"
"        }"
"    },"
"    \"Files.GetDirectory\": {"
"        \"type\": \"method\","
"        \"description\": \"\","
"        \"transport\": \"Response\","
"        \"permission\": \"ReadData\","
"        \"params\": ["
"            { \"name\": \"directory\", \"type\": \"string\", \"required\": true },"
"            { \"name\": \"media\", \"$ref\": \"Files.Media\", \"default\": \"files\" }"
"        ],"
"        \"returns\": {"
"            \"type\": \"object\","
"            \"properties\": {"
"                \"limits\": { \"$ref\": \"List.LimitsReturned\", \"required\": true },"
"                \"files\": { \"type\": \"array\", \"id\": \"Files.Items\","
"                    \"items\": { \"type\": \"object\","
"                        \"properties\": {"
"                            \"file\": { \"type\": \"string\", \"required\": true },"
"                            \"label\": { \"type\": \"string\", \"required\": true },"
"                            \"filetype\": { \"type\": \"string\", \"enum\": [ \"file\", \"directory\" ], \"required\": true }"
"                        }"
"                    }"
"                }"
"            }"
"        }"
"    },"
"    \"Files.AddSource\" : {"
"        \"type\": \"method\","
"        \"description\": \"Add file source\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": ["
"            { \"name\": \"label\", \"type\": \"string\", \"required\": true },"
"            { \"name\": \"path\", \"type\": \"string\", \"required\": true },"
"            { \"name\": \"media\", \"type\": \"string\", \"required\": true },"
"            { \"name\": \"scanPolicy\", \"type\": \"string\", \"required\": true, \"enum\": [ \"none\", \"once\", \"daily\", \"hourly\" ] }"
"        ],"
"        \"returns\": \"string\""
"    },"
"    \"Files.DeleteSource\" : {"
"        \"type\": \"method\","
"        \"description\": \"Delete file source\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": ["
"            { \"name\": \"label\", \"type\": \"string\", \"required\": true }"
"        ],"
"        \"returns\": \"string\""
"    },"
"    \"System.Shutdown\": {"
"        \"type\": \"method\","
"        \"description\": \"Shuts the system running XBMC down\","
"        \"transport\": \"Response\","
"        \"permission\": \"ControlPower\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"System.Suspend\": {"
"        \"type\": \"method\","
"        \"description\": \"Suspends the system running XBMC\","
"        \"transport\": \"Response\","
"        \"permission\": \"ControlPower\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"System.Hibernate\": {"
"        \"type\": \"method\","
"        \"description\": \"Puts the system running XBMC into hibernate mode\","
"        \"transport\": \"Response\","
"        \"permission\": \"ControlPower\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"System.Reboot\": {"
"        \"type\": \"method\","
"        \"description\": \"Reboots the system running XBMC\","
"        \"transport\": \"Response\","
"        \"permission\": \"ControlPower\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"System.GetInfoLabels\": {"
"        \"type\": \"method\","
"        \"description\": \"Retrieve info labels about the system\","
"        \"transport\": \"Response\","
"        \"permission\": \"ReadData\","
"        \"params\": ["
"            { \"name\": \"labels\", \"type\": \"array\", \"required\": true, \"items\": { \"type\": \"string\" }, \"minItems\": 1, \"description\": \"See http://wiki.xbmc.org/index.php?title=InfoLabels for a list of possible info labels\" }"
"        ],"
"        \"returns\": {"
"            \"type\": \"object\","
"            \"description\": \"List of key-value pairs of the retrieved info labels\""
"        }"
"    },"
"    \"System.GetInfoBooleans\": {"
"        \"type\": \"method\","
"        \"description\": \"Retrieve info booleans about the system\","
"        \"transport\": \"Response\","
"        \"permission\": \"ReadData\","
"        \"params\": ["
"            { \"name\": \"booleans\", \"type\": \"array\", \"required\": true, \"items\": { \"type\": \"string\" }, \"minItems\": 1, \"description\": \"\" }"
"        ],"
"        \"returns\": {"
"            \"type\": \"object\","
"            \"description\": \"List of key-value pairs of the retrieved info booleans\""
"        }"
"    },"
"    \"Input.Left\": {"
"        \"type\": \"method\","
"        \"description\": \"Navigate left in GUI\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"Input.Right\": {"
"        \"type\": \"method\","
"        \"description\": \"Navigate right in GUI\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"Input.Down\": {"
"        \"type\": \"method\","
"        \"description\": \"Navigate down in GUI\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"Input.Up\": {"
"        \"type\": \"method\","
"        \"description\": \"Navigate up in GUI\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"Input.Select\": {"
"        \"type\": \"method\","
"        \"description\": \"Select current item in GUI\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"Input.Back\": {"
"        \"type\": \"method\","
"        \"description\": \"Goes back in GUI\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"Input.Home\": {"
"        \"type\": \"method\","
"        \"description\": \"Goes to home window in GUI\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"XBMC.GetVolume\": {"
"        \"type\": \"method\","
"        \"description\": \"Retrieve the current volume\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": \"integer\""
"    },"
"    \"XBMC.SetVolume\": {"
"        \"type\": \"method\","
"        \"description\": \"Set the current volume\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": ["
"            { \"name\": \"value\", \"type\": \"integer\", \"minimum\": 0, \"maximum\": 100, \"required\": true }"
"        ],"
"        \"returns\": \"integer\""
"    },"
"    \"XBMC.ToggleMute\": {"
"        \"type\": \"method\","
"        \"description\": \"Toggle mute/unmute\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": [],"
"        \"returns\": { \"type\": \"integer\", \"description\": \"New volume\" }"
"    },"
"    \"XBMC.Play\": {"
"        \"type\": \"method\","
"        \"description\": \"Starts playback of the given file\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": ["
"            { \"name\": \"file\", \"type\": \"string\", \"required\": true }"
"            ,"
"            { \"name\": \"contenttype\", \"type\": \"string\", \"required\": false }"
"        ],"
"        \"returns\": \"string\""
"    },"
"    \"XBMC.StartSlideshow\": {"
"        \"type\": \"method\","
"        \"description\": \"Starts slideshow with the images from the given directory\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": ["
"            { \"name\": \"directory\", \"type\": \"string\", \"required\": true },"
"            { \"name\": \"random\", \"type\": \"boolean\", \"default\": true },"
"            { \"name\": \"recursive\", \"type\": \"boolean\", \"default\": true }"
"        ],"
"        \"returns\": \"string\""
"    },"
"    \"XBMC.Quit\": {"
"        \"type\": \"method\","
"        \"description\": \"Quit XBMC\","
"        \"transport\": \"Response\","
"        \"permission\": \"ControlPower\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    },"
"    \"Device.PairChallenge\" : {"
"        \"type\": \"method\","
"        \"description\": \"Send a challenge string for pairing\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": ["
"            { \"name\": \"deviceid\", \"type\": \"string\", \"required\": true },"
"            { \"name\": \"applicationid\", \"type\": \"string\", \"required\": true },"
"            { \"name\": \"label\", \"type\": \"string\", \"required\": true },"
"            { \"name\": \"icon\", \"type\": \"string\", \"required\": false },"
"            { \"name\": \"type\", \"type\": \"string\", \"required\": true, \"enum\": [ \"tablet\", \"phone\", \"remote\", \"other\" ] }"
"        ],"
"        \"returns\": \"string\""
"    },"
"    \"Device.PairResponse\" : {"
"        \"type\": \"method\","
"        \"description\": \"Send a challenge response string during pairing\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": ["
"            { \"name\": \"deviceid\", \"type\": \"string\", \"required\": true },"
"            { \"name\": \"code\", \"type\": \"string\", \"required\": true }"
"        ],"
"        \"returns\": \"string\""
"    },"
"    \"Device.Unpair\" : {"
"        \"type\": \"method\","
"        \"description\": \"Unpair a paired device\","
"        \"transport\": \"Response\","
"        \"permission\": \"ReadData\","
"        \"params\": ["
"            { \"name\": \"deviceid\", \"type\": \"string\", \"required\": true }"
"        ],"
"        \"returns\": \"string\""
"    },"
"    \"Device.Connect\" : {"
"        \"type\": \"method\","
"        \"description\": \"Connect a paired device, authorizing additional JSON calls\","
"        \"transport\": \"Response\","
"        \"permission\": \"None\","
"        \"params\": ["
"            { \"name\": \"deviceid\", \"type\": \"string\", \"required\": true }"
"        ],"
"        \"returns\": \"string\""
"    },"
"    \"GUI.TextFieldSet\" : {"
"        \"type\": \"method\","
"        \"description\": \"Set a value of a text field\","
"        \"transport\": \"Response\","
"        \"permission\": \"Navigate\","
"        \"params\": ["
"            { \"name\": \"text\", \"type\": \"string\", \"required\": true }"
"        ],"
"        \"returns\": \"string\""
"    },"
"    \"GUI.NotificationShow\" : {"
"        \"type\": \"method\","
"        \"description\": \"Show notification popup dialog\","
"        \"transport\": \"Response\","
"        \"permission\": \"Navigate\","
"        \"params\": ["
"            { \"name\": \"msg\", \"type\": \"string\", \"required\": true }"
"        ],"
"        \"returns\": \"string\""
"    },"
"    \"GUI.KeyboardState\" : {"
"        \"type\": \"method\","
"        \"description\": \"State of the keyboard\","
"        \"transport\": \"Response\","
"        \"permission\": \"ReadData\","
"        \"params\": [],"
"        \"returns\": {"
"            \"type\": \"object\","
"            \"properties\": {"
"                \"displayed\": { \"type\": \"boolean\" },"
"                \"text\": { \"type\": \"string\" },"
"                \"password\": { \"type\": \"boolean\" }"
"            }"
"        }"
"    },"
"    \"Input.NavigationState\" : {"
"        \"type\": \"method\","
"        \"description\": \"Return the allowed navigateion states\","
"        \"transport\": \"Response\","
"        \"permission\": \"ReadData\","
"        \"params\": [],"
"        \"returns\": {"
"            \"type\": \"object\","
"            \"properties\": {"
"                \"keys-enabled\": { \"type\": \"boolean\" },"
"                \"mouse-enabled\": { \"type\": \"boolean\" }"
"            }"
"        }"
"    },"
"    \"Input.MouseMovement\" : {"
"        \"type\": \"method\","
"        \"description\": \"Send a mouse movement event\","
"        \"transport\": \"Response\","
"        \"permission\": \"Navigate\","
"        \"params\": ["
"            { \"name\": \"deltax\", \"type\": \"integer\", \"required\": true },"
"            { \"name\": \"deltay\", \"type\": \"integer\", \"required\": true }"
"        ],"
"        \"returns\": \"string\""
"    },"
"    \"Input.MouseClick\" : {"
"        \"type\": \"method\","
"        \"description\": \"Send a mouse click event\","
"        \"transport\": \"Response\","
"        \"permission\": \"Navigate\","
"        \"params\": [],"
"        \"returns\": \"string\""
"    }"
"  }"
  ;

  const char* const JSON_NOTIFICATION_DESCRIPTION =
  "{"

  "}";
}
