INCLUDES =-I../../xbmc/utils -I../../guilib -I../../xbmc/linux -I../../xbmc/lib/libsquish
DEFINES =  -D_LINUX

OBJS = \
	SDL_anigif.o \
	XBTFWriter.o \
	XBMCTex.o \
	XBTF.o

TARGET = TexturePacker
CLEAN_FILES=$(TARGET)

$(TARGET) : $(OBJS)
	g++ -o $(TARGET) $(OBJS) libsquish-i486-linux.a -llzo2 -lSDL -lSDL_image

.cpp.o:
	g++ -c $(DEFINES) $(INCLUDES) $< -o $@

clean:
	rm -f $(TARGET) $(OBJS)
